[package]
name = "optimization"
version = "0.1.0"
authors = ["akhilsadam <sadam.akhil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.42"